-- Minimal requirements for tables used in this project's data import part
-- Include the definition of the view for web services

-- Declarations as extracted and archived from the source web service
-- Some columns are used only for filtering exports
CREATE TABLE IF NOT EXISTS "full_declaration" (
    "id_dossier" bigint PRIMARY KEY,
    "porteur" bool,
    "siret_port" char(14),
    "ref_urba" text,
    "type_proj" text,
    "surf_socle" decimal(17, 4),
    "etat" text,
    "puiss_max" int,
    "date_depot" date,
    "date_deliv" date,
    "date_insta" date,
    "duree_exp" int,
    "adresse" text,
    "num_parcelles" text,
    "surf_occup" decimal(17, 4),
    "surf_terr" decimal(17, 4),
    "localisat" text,
    "sol_nature" text,
    "sol_detail" text,
    "usage_terr" text,
    "type_agri" text,
    "agri_ini" text,
    "agri_resid" text,
    "ancrage" text,
    "cloture" text,
    "revetement" text,
    "haut_pann" decimal(6, 3),
    "espacement" decimal(8, 3),
    "nat_pieux" bool,
    "transit" bool,
    "agrivolt" bool,
    "ex_date" bool,
    "ex_agriv" bool,
    "ex_techniq" bool,
    "creation" timestamp (0) with time zone,
    "geom" geometry(GEOMETRYCOLLECTION,2154),
    "dern_modif" timestamp (0) with time zone,
    "archive" bool,
    "supprime" bool
);